SELECT CITY, len_city FROM (
SELECT CITY, LENGTH(CITY) as len_city, ROW_NUMBER() OVER(ORDER BY LENGTH(CITY), CITY) AS row_num
FROM STATION) as st
WHERE row_num = 1
UNION 
SELECT CITY, len_city FROM (
SELECT CITY, LENGTH(CITY) as len_city, ROW_NUMBER() OVER(ORDER BY LENGTH(CITY) DESC, CITY) AS row_num
FROM STATION) as st
WHERE row_num = 1